using System.Globalization;
using EngineeringHub.Api.Data;
using EngineeringHub.Api.Dtos;
using EngineeringHub.Api.Models;
using EngineeringHub.Api.Services;
using Microsoft.EntityFrameworkCore;
using SonAero.Platform.Security;

namespace EngineeringHub.Api.Endpoints;

public static class ToolingEndpoints
{
    private const long MaxDocumentBytes = 100 * 1024 * 1024;

    public static void MapToolingEndpoints(this RouteGroupBuilder api)
    {
        api.MapGet("/tools", ListAsync).RequireAuthorization(EngineeringPermissions.ToolingView);
        api.MapGet("/tools/{id:int}", GetAsync).RequireAuthorization(EngineeringPermissions.ToolingView);
        api.MapPost("/tools", CreateAsync).RequireAuthorization(EngineeringPermissions.ToolingRecordsManage);
        api.MapPut("/tools/{id:int}", UpdateAsync).RequireAuthorization(EngineeringPermissions.ToolingRecordsManage);
        api.MapPut("/tools/{id:int}/archive", UpdateArchiveStatusAsync)
            .RequireAuthorization(EngineeringPermissions.ToolingArchiveManage);
        api.MapPost("/tools/{id:int}/checkout", CheckoutAsync).RequireAuthorization(EngineeringPermissions.ToolingCustodyManage);
        api.MapPost("/tools/{id:int}/checkin", CheckinAsync).RequireAuthorization(EngineeringPermissions.ToolingCustodyManage);
        api.MapPost("/tools/{id:int}/documents", UploadDocumentAsync)
            .DisableAntiforgery().RequireAuthorization(EngineeringPermissions.ToolingDocumentsManage);
        api.MapGet("/tool-documents/{id:long}/file", DownloadDocumentAsync)
            .RequireAuthorization(EngineeringPermissions.ToolingView);
        api.MapGet("/tool-locations", ListLocationsAsync).RequireAuthorization(EngineeringPermissions.ToolingView);
        api.MapPost("/tool-locations", CreateLocationAsync).RequireAuthorization(EngineeringPermissions.ToolingLocationsManage);
        api.MapPut("/tool-locations/{id:int}/status", UpdateLocationStatusAsync).RequireAuthorization(EngineeringPermissions.ToolingLocationsManage);
        api.MapGet("/tools/catalog-export", ExportCatalogAsync)
            .RequireAuthorization(EngineeringPermissions.ToolingAuditImport);
        api.MapPost("/tools/catalog-import/validate", ValidateCatalogAsync)
            .DisableAntiforgery().RequireAuthorization(EngineeringPermissions.ToolingAuditImport);
        api.MapGet("/tools/catalog-import/{reviewId}/workbook", DownloadCatalogReviewAsync)
            .RequireAuthorization(EngineeringPermissions.ToolingAuditImport);
        api.MapPost("/tools/catalog-import/{reviewId}/apply", ApplyCatalogAsync)
            .RequireAuthorization(EngineeringPermissions.ToolingAuditImport);
    }

    private static async Task<IResult> ExportCatalogAsync(
        EngineeringDbContext db,
        ToolCatalogWorkbookService workbooks,
        CancellationToken cancellationToken)
    {
        var workbook = await workbooks.ExportAsync(db, cancellationToken);
        return Results.File(workbook, ToolCatalogWorkbookService.ContentType, ToolCatalogWorkbookService.TemplateFileName);
    }

    private static async Task<IResult> ValidateCatalogAsync(
        HttpRequest request,
        EngineeringDbContext db,
        ToolCatalogWorkbookService workbooks,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        if (!request.HasFormContentType)
            return Results.BadRequest(new ErrorDto("FormRequired", "Use multipart form data."));
        var form = await request.ReadFormAsync(cancellationToken);
        var file = form.Files.GetFile("file");
        if (file is null || file.Length == 0)
            return Results.BadRequest(new ErrorDto("CatalogRequired", "Select the completed tool catalogue workbook."));
        if (!string.Equals(Path.GetExtension(file.FileName), ".xlsx", StringComparison.OrdinalIgnoreCase))
            return Results.BadRequest(new ErrorDto("CatalogFormat", "Upload the .xlsx workbook generated by the tool catalogue export."));
        if (file.Length > 15 * 1024 * 1024)
            return Results.BadRequest(new ErrorDto("CatalogTooLarge", "Tool catalogue workbooks must be 15 MB or smaller."));
        try
        {
            await using var stream = new MemoryStream();
            await file.CopyToAsync(stream, cancellationToken);
            return Results.Ok(await workbooks.ValidateAsync(db, stream.ToArray(), file.FileName, Actor(http), cancellationToken));
        }
        catch (ToolCatalogValidationException exception)
        {
            return Results.BadRequest(new ErrorDto("CatalogInvalid", exception.Message));
        }
    }

    private static IResult DownloadCatalogReviewAsync(
        string reviewId,
        ToolCatalogWorkbookService workbooks,
        HttpContext http)
    {
        try
        {
            var workbook = workbooks.BuildReviewWorkbook(reviewId, Actor(http));
            return Results.File(
                workbook,
                ToolCatalogWorkbookService.ContentType,
                $"Tool-Catalogue-Review-{reviewId[..Math.Min(8, reviewId.Length)]}.xlsx");
        }
        catch (ToolCatalogValidationException exception)
        {
            return Results.BadRequest(new ErrorDto("CatalogReviewUnavailable", exception.Message));
        }
    }

    private static async Task<IResult> ApplyCatalogAsync(
        string reviewId,
        ToolCatalogApplyDto dto,
        EngineeringDbContext db,
        ToolCatalogWorkbookService workbooks,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        try
        {
            return Results.Ok(await workbooks.ApplyAsync(
                db, reviewId, Actor(http), dto.ContinueWithErrors, cancellationToken));
        }
        catch (ToolCatalogConflictException exception)
        {
            return Results.Conflict(new ErrorDto("CatalogChanged", exception.Message));
        }
        catch (ToolCatalogValidationException exception)
        {
            return Results.BadRequest(new ErrorDto("CatalogInvalid", exception.Message));
        }
    }

    private static async Task<IResult> ListAsync(
        string? query,
        bool? includeArchived,
        EngineeringDbContext db,
        CancellationToken cancellationToken)
    {
        var tools = await db.Tools.AsNoTracking()
            .Include(x => x.CurrentLocation)
            .Include(x => x.HomeLocationAssignment).ThenInclude(x => x!.Location)
            .Include(x => x.Documents)
            .Include(x => x.PartNumbers)
            .OrderBy(x => x.ToolNumber)
            .ToListAsync(cancellationToken);
        if (includeArchived != true) tools = tools.Where(tool => !tool.IsArchived).ToList();
        var normalized = query?.Trim();
        if (!string.IsNullOrWhiteSpace(normalized))
            tools = tools.Where(tool => Matches(tool, normalized)).ToList();

        var summaries = tools.Select(ToSummary).ToList();
        var auditLimit = DateTime.UtcNow.Date.AddYears(-1);
        return Results.Ok(new ToolingDashboardDto(
            summaries,
            summaries.Count,
            summaries.Count(x => x.CustodyStatus == nameof(ToolCustodyStatus.InStorage)),
            summaries.Count(x => x.CustodyStatus == nameof(ToolCustodyStatus.CheckedOut)),
            summaries.Count(x => x.CustodyStatus == nameof(ToolCustodyStatus.OutsideProcessing)),
            summaries.Count(x => !x.LastAuditDate.HasValue || x.LastAuditDate.Value < auditLimit)));
    }

    private static async Task<IResult> GetAsync(int id, EngineeringDbContext db, CancellationToken cancellationToken)
    {
        var tool = await db.Tools.AsNoTracking()
            .Include(x => x.CurrentLocation)
            .Include(x => x.HomeLocationAssignment).ThenInclude(x => x!.Location)
            .Include(x => x.Movements).ThenInclude(x => x.Location)
            .Include(x => x.Documents)
            .Include(x => x.PartNumbers)
            .Include(x => x.AuditEntries)
            .AsSplitQuery()
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        return tool is null ? Results.NotFound() : Results.Ok(ToDetail(tool));
    }

    private static async Task<IResult> CreateAsync(
        ToolUpsertDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var validation = Validate(dto);
        if (validation is not null) return validation;
        if (dto.IsArchived == true)
            return Results.BadRequest(new ErrorDto("ArchiveActionRequired", "Create the active tool record first, then use the manager-controlled archive action."));
        var normalizedNumber = Normalize(dto.ToolNumber);
        if (await db.Tools.AnyAsync(x => x.NormalizedToolNumber == normalizedNumber, cancellationToken))
            return Results.Conflict(new ErrorDto("DuplicateToolNumber", "That tool number already exists."));
        var location = await ActiveLocationAsync(dto.HomeLocationId, db, cancellationToken);
        if (location is null)
            return Results.BadRequest(new ErrorDto("LocationRequired", "Select an active physical storage location."));

        var actor = Actor(http);
        var now = DateTime.UtcNow;
        var tool = new ToolRecord
        {
            ToolNumber = dto.ToolNumber.Trim(),
            NormalizedToolNumber = normalizedNumber,
            Name = dto.Name.Trim(),
            ToolType = dto.ToolType.Trim(),
            Owner = dto.Owner.Trim(),
            Description = Clean(dto.Description),
            Notes = Clean(dto.Notes),
            HomeLocationAssignment = new ToolHomeLocation { Location = location },
            CurrentLocation = location,
            CreatedBy = actor,
            CreatedAt = now,
            UpdatedBy = actor,
            UpdatedAt = now
        };
        SetPartNumbers(tool, CleanPartNumbers(dto.PartNumbers));
        tool.Movements.Add(new ToolMovement
        {
            Type = ToolMovementType.Registered,
            Location = location,
            LocationCode = location.Code,
            Person = actor,
            Purpose = "Initial tool registration",
            SignedOffBy = actor,
            RecordedAt = now
        });
        tool.AuditEntries.Add(Audit(tool, "ToolCreated", $"Created tool {tool.ToolNumber} in location {location.Code}.", actor));
        db.Tools.Add(tool);
        await db.SaveChangesAsync(cancellationToken);
        return Results.Created($"/api/tools/{tool.Id}", ToDetail(tool));
    }

    private static async Task<IResult> UpdateAsync(
        int id,
        ToolUpsertDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var validation = Validate(dto);
        if (validation is not null) return validation;
        var tool = await db.Tools.Include(x => x.CurrentLocation)
            .Include(x => x.HomeLocationAssignment).ThenInclude(x => x!.Location)
            .Include(x => x.Movements).Include(x => x.PartNumbers).Include(x => x.AuditEntries)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (tool is null) return Results.NotFound();
        if (dto.Version.HasValue && dto.Version != tool.Version)
            return Results.Conflict(new ErrorDto("ToolChanged", "This tool changed after you opened it. Refresh and try again."));
        if (dto.IsArchived.HasValue && dto.IsArchived.Value != tool.IsArchived)
            return Results.BadRequest(new ErrorDto("ArchiveActionRequired", "Use the manager-controlled archive or restore action to change this tool's archive status."));
        var normalizedNumber = Normalize(dto.ToolNumber);
        if (await db.Tools.AnyAsync(x => x.Id != id && x.NormalizedToolNumber == normalizedNumber, cancellationToken))
            return Results.Conflict(new ErrorDto("DuplicateToolNumber", "That tool number already exists."));
        var actor = Actor(http);
        var homeLocation = await ActiveLocationAsync(dto.HomeLocationId, db, cancellationToken);
        if (homeLocation is null)
            return Results.BadRequest(new ErrorDto("LocationRequired", "Select an active default check-in location."));
        var description = Clean(dto.Description);
        var notes = Clean(dto.Notes);
        var partNumbers = CleanPartNumbers(dto.PartNumbers);
        var changes = DescribeToolChanges(tool, dto, homeLocation, partNumbers, description, notes);
        if (tool.HomeLocationAssignment?.LocationId != homeLocation.Id)
        {
            if (tool.HomeLocationAssignment is null)
                tool.HomeLocationAssignment = new ToolHomeLocation { Tool = tool, Location = homeLocation };
            else
                tool.HomeLocationAssignment.Location = homeLocation;
            if (tool.CustodyStatus == ToolCustodyStatus.InStorage)
            {
                tool.CurrentLocation = homeLocation;
                tool.Movements.Add(new ToolMovement
                {
                    Type = ToolMovementType.Relocated,
                    Location = homeLocation,
                    LocationCode = homeLocation.Code,
                    Person = actor,
                    Purpose = "Default check-in location updated with tool metadata",
                    SignedOffBy = actor,
                    RecordedAt = DateTime.UtcNow
                });
            }
        }
        tool.ToolNumber = dto.ToolNumber.Trim();
        tool.NormalizedToolNumber = normalizedNumber;
        tool.Name = dto.Name.Trim();
        tool.ToolType = dto.ToolType.Trim();
        tool.Owner = dto.Owner.Trim();
        tool.Description = description;
        tool.Notes = notes;
        SetPartNumbers(tool, partNumbers);
        tool.UpdatedBy = actor;
        tool.UpdatedAt = DateTime.UtcNow;
        tool.Version++;
        tool.AuditEntries.Add(Audit(tool, "ToolUpdated", changes.Count > 0
            ? $"Updated {string.Join("; ", changes)}."
            : "Saved the tool record without changing controlled values.", actor));
        await db.SaveChangesAsync(cancellationToken);
        return Results.Ok(new { tool.Id, tool.Version });
    }

    private static async Task<IResult> UpdateArchiveStatusAsync(
        int id,
        ToolArchiveStatusDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var tool = await db.Tools
            .Include(x => x.AuditEntries)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (tool is null) return Results.NotFound();
        if (dto.Version.HasValue && dto.Version != tool.Version)
            return Results.Conflict(new ErrorDto("ToolChanged", "This tool changed after you opened it. Refresh and try again."));
        if (dto.IsArchived == tool.IsArchived)
            return Results.Ok(new { tool.Id, tool.Version, tool.IsArchived });
        if (dto.IsArchived && tool.CustodyStatus != ToolCustodyStatus.InStorage)
            return Results.Conflict(new ErrorDto("ToolInCustody", "Check the tool into storage before archiving it."));

        var actor = Actor(http);
        tool.IsArchived = dto.IsArchived;
        tool.UpdatedBy = actor;
        tool.UpdatedAt = DateTime.UtcNow;
        tool.Version++;
        tool.AuditEntries.Add(Audit(
            tool,
            dto.IsArchived ? "ToolArchived" : "ToolRestored",
            dto.IsArchived
                ? $"Archived tool {tool.ToolNumber}. Checkout and release actions are disabled until the tool is restored."
                : $"Restored tool {tool.ToolNumber} to active service. Authorized custody actions are available again.",
            actor));
        await db.SaveChangesAsync(cancellationToken);
        return Results.Ok(new { tool.Id, tool.Version, tool.IsArchived });
    }

    private static async Task<IResult> CheckoutAsync(
        int id,
        ToolCheckoutDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var tool = await db.Tools.Include(x => x.Movements).Include(x => x.AuditEntries)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (tool is null) return Results.NotFound();
        if (tool.IsArchived) return Results.Conflict(new ErrorDto("ToolArchived", "Archived tools cannot be checked out."));
        if (tool.CustodyStatus != ToolCustodyStatus.InStorage)
            return Results.Conflict(new ErrorDto("ToolAlreadyCheckedOut", "This tool is already checked out."));
        if (!dto.InspectionConfirmed)
            return Results.BadRequest(new ErrorDto("InspectionRequired", "Confirm the tool was inspected before release and sign off on the movement."));
        if (string.IsNullOrWhiteSpace(dto.Person))
            return Results.BadRequest(new ErrorDto("PersonRequired", "Enter the person responsible for the tool."));

        var outside = string.Equals(dto.DestinationType, "vendor", StringComparison.OrdinalIgnoreCase);
        ToolLocation? location = null;
        var vendor = Clean(dto.Vendor);
        if (outside)
        {
            if (string.IsNullOrWhiteSpace(vendor))
                return Results.BadRequest(new ErrorDto("VendorRequired", "Specify the outside processing vendor."));
        }
        else
        {
            location = await ActiveLocationAsync(dto.LocationId, db, cancellationToken);
            if (location is null)
                return Results.BadRequest(new ErrorDto("DestinationRequired", "Select an active destination location."));
        }

        var actor = Actor(http);
        var now = DateTime.UtcNow;
        tool.CustodyStatus = outside ? ToolCustodyStatus.OutsideProcessing : ToolCustodyStatus.CheckedOut;
        tool.CurrentLocation = location;
        tool.CurrentHolder = dto.Person.Trim();
        tool.CurrentVendor = outside ? vendor : null;
        tool.CheckedOutAt = now;
        tool.UpdatedBy = actor;
        tool.UpdatedAt = now;
        tool.Version++;
        tool.Movements.Add(new ToolMovement
        {
            Type = outside ? ToolMovementType.SentToVendor : ToolMovementType.CheckedOut,
            Location = location,
            LocationCode = location?.Code,
            Vendor = outside ? vendor : null,
            Person = dto.Person.Trim(),
            Purpose = Clean(dto.Purpose),
            InspectionConfirmed = true,
            InspectionNotes = Clean(dto.InspectionNotes),
            SignedOffBy = actor,
            RecordedAt = now
        });
        var destination = outside ? $"vendor {vendor}" : $"location {location!.Code}";
        tool.AuditEntries.Add(Audit(tool, "ToolReleased", $"Released to {destination} after inspection sign-off by {actor}.", actor));
        await db.SaveChangesAsync(cancellationToken);
        return Results.Ok(new { tool.Id, status = tool.CustodyStatus.ToString(), tool.Version });
    }

    private static async Task<IResult> CheckinAsync(
        int id,
        ToolCheckinDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var tool = await db.Tools.Include(x => x.Movements).Include(x => x.AuditEntries)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (tool is null) return Results.NotFound();
        if (tool.CustodyStatus == ToolCustodyStatus.InStorage)
            return Results.Conflict(new ErrorDto("ToolAlreadyInStorage", "This tool is already checked in."));
        var location = await ActiveLocationAsync(dto.LocationId, db, cancellationToken);
        if (location is null)
            return Results.BadRequest(new ErrorDto("LocationRequired", "Select an active storage location."));

        var actor = Actor(http);
        var now = DateTime.UtcNow;
        var returningFromVendor = tool.CustodyStatus == ToolCustodyStatus.OutsideProcessing;
        tool.CustodyStatus = ToolCustodyStatus.InStorage;
        tool.CurrentLocation = location;
        tool.CurrentHolder = null;
        tool.CurrentVendor = null;
        tool.CheckedOutAt = null;
        tool.UpdatedBy = actor;
        tool.UpdatedAt = now;
        tool.Version++;
        tool.Movements.Add(new ToolMovement
        {
            Type = returningFromVendor ? ToolMovementType.ReturnedFromVendor : ToolMovementType.CheckedIn,
            Location = location,
            LocationCode = location.Code,
            Person = Clean(dto.Person) ?? actor,
            Purpose = Clean(dto.Purpose),
            SignedOffBy = actor,
            RecordedAt = now
        });
        tool.AuditEntries.Add(Audit(tool, "ToolCheckedIn", $"Checked into storage location {location.Code}.", actor));
        await db.SaveChangesAsync(cancellationToken);
        return Results.Ok(new { tool.Id, status = tool.CustodyStatus.ToString(), tool.Version });
    }

    private static async Task<IResult> UploadDocumentAsync(
        int id,
        HttpRequest request,
        EngineeringDbContext db,
        IDrawingFileStore files,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        if (!request.HasFormContentType)
            return Results.BadRequest(new ErrorDto("FormRequired", "Use multipart form data."));
        var tool = await db.Tools.Include(x => x.Documents).Include(x => x.AuditEntries)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (tool is null) return Results.NotFound();
        var form = await request.ReadFormAsync(cancellationToken);
        if (!Enum.TryParse<ToolDocumentKind>(form["kind"], true, out var kind))
            return Results.BadRequest(new ErrorDto("DocumentKindRequired", "Select Receiving or Shipping."));
        if (!DateTime.TryParseExact(form["documentDate"].ToString(), "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out var documentDate))
            return Results.BadRequest(new ErrorDto("DocumentDateRequired", "Enter a valid document date."));
        if (documentDate.Date > DateTime.UtcNow.Date)
            return Results.BadRequest(new ErrorDto("FutureDocumentDate", "Document dates cannot be in the future."));
        var file = form.Files.GetFile("document");
        if (file is null || file.Length == 0)
            return Results.BadRequest(new ErrorDto("DocumentRequired", "Select a receiving or shipping document."));
        if (file.Length > MaxDocumentBytes)
            return Results.BadRequest(new ErrorDto("FileTooLarge", "Tool documents must be 100 MB or smaller."));
        var metadata = await SupplementalFileValidation.InspectAsync(file, cancellationToken);
        if (metadata is null)
            return Results.BadRequest(new ErrorDto("UnsupportedDocument", "Select a supported PDF, image, Office, text, CAD, STEP/IGES, or ZIP document."));

        StoredToolDocument stored;
        try
        {
            stored = await files.StoreToolDocumentAsync(tool.Id, tool.ToolNumber, kind.ToString(), file, cancellationToken);
        }
        catch (Exception exception)
        {
            return Results.Problem(statusCode: StatusCodes.Status503ServiceUnavailable, title: "Tool document storage unavailable", detail: exception.Message);
        }

        var actor = Actor(http);
        var document = new ToolDocument
        {
            Kind = kind,
            DocumentNumber = Clean(form["documentNumber"]),
            OriginalFileName = Path.GetFileName(file.FileName),
            StoredFilePath = stored.RelativePath,
            FileType = metadata.ContentType,
            FileSize = file.Length,
            FileHash = stored.Hash,
            Notes = Clean(form["notes"]),
            DocumentDate = documentDate.Date,
            UploadedBy = actor,
            UploadedAt = DateTime.UtcNow
        };
        tool.Documents.Add(document);
        tool.AuditEntries.Add(Audit(tool, "ToolDocumentUploaded", $"Uploaded {kind.ToString().ToLowerInvariant()} document {document.OriginalFileName} dated {document.DocumentDate:yyyy-MM-dd}; SHA-256 {stored.Hash}.", actor));
        try
        {
            await db.SaveChangesAsync(cancellationToken);
        }
        catch
        {
            await using var staged = await files.StageDeletionAsync(stored.RelativePath, cancellationToken);
            await staged.CompleteAsync(cancellationToken);
            throw;
        }
        return Results.Created($"/api/tool-documents/{document.Id}/file", ToDocument(document));
    }

    private static async Task<IResult> DownloadDocumentAsync(
        long id,
        bool? download,
        EngineeringDbContext db,
        IDrawingFileStore files,
        CancellationToken cancellationToken)
    {
        var document = await db.ToolDocuments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (document is null) return Results.NotFound();
        var path = await files.ResolvePathAsync(document.StoredFilePath, cancellationToken);
        if (!File.Exists(path)) return Results.NotFound();
        return download != true && (document.FileType == "application/pdf" || document.FileType.StartsWith("image/", StringComparison.OrdinalIgnoreCase))
            ? Results.File(path, document.FileType, enableRangeProcessing: true)
            : Results.File(path, document.FileType, document.OriginalFileName, enableRangeProcessing: true);
    }

    private static async Task<IResult> ListLocationsAsync(EngineeringDbContext db, CancellationToken cancellationToken)
    {
        var records = await db.ToolLocations.AsNoTracking()
            .Include(location => location.Tools)
            .Include(location => location.HomeAssignments).ThenInclude(assignment => assignment.Tool)
            .OrderBy(location => location.Code)
            .ToListAsync(cancellationToken);
        var locations = records.Select(location => new ToolLocationDto(
            location.Id, location.Code, location.Description, location.IsActive,
            location.Tools.Count(tool => !tool.IsArchived && tool.CustodyStatus == ToolCustodyStatus.InStorage),
            location.HomeAssignments.Count(assignment => !assignment.Tool.IsArchived), location.CreatedBy, location.CreatedAt)).ToList();
        return Results.Ok(locations);
    }

    private static async Task<IResult> CreateLocationAsync(
        ToolLocationCreateDto dto,
        EngineeringDbContext db,
        HttpContext http,
        CancellationToken cancellationToken)
    {
        var code = dto.Code?.Trim();
        if (string.IsNullOrWhiteSpace(code) || code.Length > 60)
            return Results.BadRequest(new ErrorDto("LocationCodeRequired", "Enter a location code up to 60 characters."));
        var normalized = Normalize(code);
        if (await db.ToolLocations.AnyAsync(x => x.NormalizedCode == normalized, cancellationToken))
            return Results.Conflict(new ErrorDto("DuplicateLocation", "That location code already exists."));
        var location = new ToolLocation
        {
            Code = code.ToUpperInvariant(),
            NormalizedCode = normalized,
            Description = Clean(dto.Description),
            CreatedBy = Actor(http),
            CreatedAt = DateTime.UtcNow
        };
        db.ToolLocations.Add(location);
        await db.SaveChangesAsync(cancellationToken);
        return Results.Created($"/api/tool-locations/{location.Id}", new ToolLocationDto(location.Id, location.Code, location.Description, true, 0, 0, location.CreatedBy, location.CreatedAt));
    }

    private static async Task<IResult> UpdateLocationStatusAsync(
        int id,
        ToolLocationStatusDto dto,
        EngineeringDbContext db,
        CancellationToken cancellationToken)
    {
        var location = await db.ToolLocations.Include(x => x.Tools).Include(x => x.HomeAssignments).ThenInclude(assignment => assignment.Tool)
            .SingleOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (location is null) return Results.NotFound();
        if (!dto.IsActive && (location.Tools.Any(tool => !tool.IsArchived && tool.CustodyStatus == ToolCustodyStatus.InStorage) ||
                              location.HomeAssignments.Any(assignment => !assignment.Tool.IsArchived)))
            return Results.Conflict(new ErrorDto("LocationInUse", "Move stored tools and reassign every active tool's default check-in location before disabling this location."));
        location.IsActive = dto.IsActive;
        await db.SaveChangesAsync(cancellationToken);
        return Results.NoContent();
    }

    private static List<string> DescribeToolChanges(
        ToolRecord tool,
        ToolUpsertDto dto,
        ToolLocation homeLocation,
        IReadOnlyList<string> partNumbers,
        string? description,
        string? notes)
    {
        var changes = new List<string>();
        AddChange(changes, "tool number", tool.ToolNumber, dto.ToolNumber.Trim());
        AddChange(changes, "name", tool.Name, dto.Name.Trim());
        AddChange(changes, "type", tool.ToolType, dto.ToolType.Trim());
        AddChange(changes, "owner", tool.Owner, dto.Owner.Trim());
        AddChange(changes, "description", tool.Description, description);
        AddChange(changes, "notes", tool.Notes, notes);
        AddChange(changes, "default check-in location", tool.HomeLocationAssignment?.Location.Code, homeLocation.Code);
        AddChange(changes, "part numbers", JoinPartNumbers(tool.PartNumbers.Select(x => x.PartNumber)), JoinPartNumbers(partNumbers));
        return changes;
    }

    private static void AddChange(List<string> changes, string label, string? before, string? after)
    {
        if (string.Equals(before, after, StringComparison.Ordinal)) return;
        changes.Add($"{label} from {AuditValue(before)} to {AuditValue(after)}");
    }

    private static string AuditValue(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "(blank)";
        var compact = string.Join(' ', value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
        return $"'{(compact.Length <= 120 ? compact : compact[..117] + "...")}'";
    }

    private static IResult? Validate(ToolUpsertDto dto)
    {
        if (string.IsNullOrWhiteSpace(dto.ToolNumber) || dto.ToolNumber.Trim().Length > 100)
            return Results.BadRequest(new ErrorDto("ToolNumberRequired", "Enter a tool number up to 100 characters."));
        if (string.IsNullOrWhiteSpace(dto.Name))
            return Results.BadRequest(new ErrorDto("ToolNameRequired", "Enter a tool name."));
        if (string.IsNullOrWhiteSpace(dto.ToolType))
            return Results.BadRequest(new ErrorDto("ToolTypeRequired", "Enter a tool type."));
        if (string.IsNullOrWhiteSpace(dto.Owner))
            return Results.BadRequest(new ErrorDto("ToolOwnerRequired", "Enter the tool owner, such as Son-Aero or a customer."));
        if (CleanPartNumbers(dto.PartNumbers).Count == 0)
            return Results.BadRequest(new ErrorDto("ToolPartRequired", "Add at least one associated part number."));
        return null;
    }

    private static async Task<ToolLocation?> ActiveLocationAsync(int? id, EngineeringDbContext db, CancellationToken cancellationToken) =>
        id.HasValue ? await db.ToolLocations.SingleOrDefaultAsync(x => x.Id == id && x.IsActive, cancellationToken) : null;

    private static bool Matches(ToolRecord tool, string query)
    {
        var values = new[]
        {
            tool.ToolNumber, tool.Name, tool.ToolType, tool.Owner, tool.Description, tool.Notes,
            tool.HomeLocationAssignment?.Location.Code, tool.HomeLocationAssignment?.Location.Description,
            tool.CurrentLocation?.Code, tool.CurrentLocation?.Description, tool.CurrentHolder,
            tool.CurrentVendor, tool.CustodyStatus.ToString()
        }.Concat(tool.PartNumbers.Select(part => part.PartNumber))
            .Concat(tool.Documents.SelectMany(document => new[] { document.DocumentNumber, document.OriginalFileName, document.Notes }));
        return values.Any(value => value?.Contains(query, StringComparison.OrdinalIgnoreCase) == true);
    }

    internal static ToolSummaryDto ToSummary(ToolRecord tool) => new(
        tool.Id, tool.ToolNumber, tool.Name, tool.ToolType, tool.Owner, tool.IsArchived,
        tool.CustodyStatus.ToString(), tool.HomeLocationAssignment?.LocationId, tool.HomeLocationAssignment?.Location.Code,
        tool.CurrentLocationId, tool.CurrentLocation?.Code,
        tool.CurrentHolder, tool.CurrentVendor, tool.CheckedOutAt, tool.LastAuditDate,
        tool.PartNumbers.Select(x => x.PartNumber).OrderBy(x => x, StringComparer.OrdinalIgnoreCase).ToList(),
        tool.Documents.Count, tool.Notes);

    internal static IReadOnlyList<string> CleanPartNumbers(IEnumerable<string>? values) =>
        (values ?? [])
            .SelectMany(value => value.Split([',', ';', '\n', '\r'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .Where(value => value.Length is > 0 and <= 100)
            .GroupBy(Normalize, StringComparer.OrdinalIgnoreCase)
            .Select(group => group.First())
            .OrderBy(value => value, StringComparer.OrdinalIgnoreCase)
            .ToList();

    internal static void SetPartNumbers(ToolRecord tool, IReadOnlyList<string> partNumbers)
    {
        var desired = partNumbers.ToDictionary(Normalize, StringComparer.OrdinalIgnoreCase);
        tool.PartNumbers.RemoveAll(part => !desired.ContainsKey(part.NormalizedPartNumber));
        foreach (var pair in desired.Where(pair => tool.PartNumbers.All(part => part.NormalizedPartNumber != pair.Key)))
            tool.PartNumbers.Add(new ToolPartNumber { Tool = tool, PartNumber = pair.Value, NormalizedPartNumber = pair.Key });
        foreach (var part in tool.PartNumbers)
            if (desired.TryGetValue(part.NormalizedPartNumber, out var display)) part.PartNumber = display;
    }

    private static string JoinPartNumbers(IEnumerable<string> values) =>
        string.Join("; ", values.OrderBy(value => value, StringComparer.OrdinalIgnoreCase));

    private static ToolDetailDto ToDetail(ToolRecord tool) => new(
        ToSummary(tool), tool.Description, tool.CreatedBy, tool.CreatedAt, tool.UpdatedBy, tool.UpdatedAt, tool.Version,
        tool.Movements.OrderByDescending(x => x.RecordedAt).Select(x => new ToolMovementDto(
            x.Id, x.Type.ToString(), x.LocationCode ?? x.Location?.Code, x.Vendor, x.Person, x.Purpose,
            x.InspectionConfirmed, x.InspectionNotes, x.SignedOffBy, x.RecordedAt)).ToList(),
        tool.Documents.OrderByDescending(x => x.UploadedAt).Select(ToDocument).ToList(),
        tool.AuditEntries.OrderByDescending(x => x.OccurredAt).Select(x => new ToolAuditEntryDto(x.Id, x.Action, x.Details, x.Actor, x.OccurredAt)).ToList());

    private static ToolDocumentDto ToDocument(ToolDocument document) => new(
        document.Id, document.Kind.ToString(), document.DocumentNumber, document.OriginalFileName,
        document.FileType, document.FileSize, document.FileHash, document.Notes, document.DocumentDate,
        document.UploadedBy, document.UploadedAt);

    private static ToolAuditEntry Audit(ToolRecord tool, string action, string details, string actor) => new()
    {
        Tool = tool, Action = action, Details = details, Actor = actor, OccurredAt = DateTime.UtcNow
    };

    private static string Normalize(string value) => string.Concat(value.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit));
    private static string? Clean(string? value) => string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    private static string Actor(HttpContext http) => http.User.Identity?.Name ?? "Unknown";

}
