// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualityAssurance.Api.Data;

#nullable disable

namespace QualityAssurance.Api.Data.Migrations
{
    [DbContext(typeof(QualityAssuranceDbContext))]
    [Migration("20260813181727_InitialQualityShipping")]
    partial class InitialQualityShipping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("QualityAssurance.Api.Models.QualityAssignmentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchField")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchOperator")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchValue")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetAccountName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetGroupName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "Priority");

                    b.ToTable("QualityAssignmentRules", (string)null);
                });

            modelBuilder.Entity("QualityAssurance.Api.Models.QualityShipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedAccountName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedDisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedGroupName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByAccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DollarValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoldReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastWorkedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NextAction")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("QaArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ShipDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippedByAccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippedByDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("SourceRequestedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByAccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Customer");

                    b.HasIndex("TaskType");

                    b.HasIndex("IsShipped", "AssignedGroupId", "ShipDate");

                    b.HasIndex("IsShipped", "AssignedUserId", "CreatedAt");

                    b.ToTable("QualityShipments", (string)null);
                });

            modelBuilder.Entity("QualityAssurance.Api.Models.QualityShipmentAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId", "OccurredAt");

                    b.ToTable("QualityShipmentAuditEntries", (string)null);
                });

            modelBuilder.Entity("QualityAssurance.Api.Models.QualityShipmentAuditEntry", b =>
                {
                    b.HasOne("QualityAssurance.Api.Models.QualityShipment", "Shipment")
                        .WithMany("AuditEntries")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("QualityAssurance.Api.Models.QualityShipment", b =>
                {
                    b.Navigation("AuditEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
